### ISSUE TITLE
Quickly switch orientation

### ISSUE THREAD

**Issue by daganzdaanda** [JOSM/gridify#17]
Thanks a lot for this plugin, it works great and has replaced the terracer plugin for me!

When splitting buildings, most often a house was mapped as one piece and needs dividing into two. So the grid size will be 1 x 2 -- or 2 x 1, depending on the orientation. 
In my opinion, a button or keyboard shortcut to switch the x and y values would be a convenient time saver for this common use case. What do you think?

**Comment by jdhoek** [comment]
I was thinking of making the `×` between the numbers do that. I can't promise any due date beyond 'eventually' though (pull requests welcome of course).

**Comment by RedAuburn** [comment]
also related to this (and the main reason this would be useful) it'd be good to always split along the longest edge, instead of from the first to second node.
